name: Go Test

# トリガー
on:
  push:

jobs:
  build:
    # ランナー(ジョブを実行するサーバ)の指定
    runs-on: ubuntu-latest

    # ジョブの内容
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: 複数行runとシェル変数
      run: |
        echo hoge
        # hogehoge
        [ -f main.go ] && SRC=main.go || SRC=hoge.go
        echo "SRC=" $SRC
        sed -i -e 's/Hello/Hey/' $SRC

    - name: Build
      run: go build -v .

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: main
